export interface PartyProduct {
  code: string
  sku: string
  name: string
  category: string
  subcategory: string
  brand: string
  unit: string
  costPrice: number
  sellingPrice: number
  currentStock: number
  minStock: number
  maxStock: number
  supplierName?: string
  location: string
  mainPhoto: string
  description: string
}

export const partyProductsCatalog: PartyProduct[] = [
  {
    code: "PROD-001",
    sku: "SKU-PROD-001",
    name: "Acessórios de Animação: Tiara Orelhinha LED, Óculos Aviador e Gravata Cetim (Kit 20 Peças)",
    category: "Pista de Dança & Animação",
    subcategory: "Adereços Festivos",
    brand: "Party Animações",
    unit: "KT",
    costPrice: 45.0,
    sellingPrice: 120.0,
    currentStock: 15,
    minStock: 3,
    maxStock: 50,
    supplierName: "Distribuidora Festas",
    location: "Armário F1",
    mainPhoto: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80",
    description: "Kit completo de adereços divertidos para pista de dança contendo tiaras com luz LED, óculos coloridos aviador e gravatas de cetim com estampa.",
  },
  {
    code: "PROD-002",
    sku: "SKU-PROD-002",
    name: "Adereço Luminoso: Pulseira Neon Glowstick (Caixa com 100 Unidades)",
    category: "Pista de Dança & Animação",
    subcategory: "Neon & Glow",
    brand: "Glow Night",
    unit: "CX",
    costPrice: 25.0,
    sellingPrice: 75.0,
    currentStock: 30,
    minStock: 5,
    maxStock: 100,
    supplierName: "Illumina Festas",
    location: "Armário F2",
    mainPhoto: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=600&auto=format&fit=crop&q=80",
    description: "Tubo de pulseiras neon de luz química de alto brilho com conectores flexíveis. Cores sortidas (Verde, Rosa, Azul, Amarelo e Laranja).",
  },
  {
    code: "PROD-003",
    sku: "SKU-PROD-003",
    name: "Aparador Espelhado de Recepção com Estrutura Rosé Gold (1,60x0,80m)",
    category: "Mobiliário & Cenografia",
    subcategory: "Aparadores",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 420.0,
    sellingPrice: 980.0,
    currentStock: 3,
    minStock: 1,
    maxStock: 6,
    supplierName: "Marcenaria Artesanal",
    location: "Depósito A1",
    mainPhoto: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&auto=format&fit=crop&q=80",
    description: "Aparador retangular sofisticado com tampo e laterais espelhadas em vidro bisotê 4mm e estrutura metálica pintada em rosé gold brilhante.",
  },
  {
    code: "PROD-004",
    sku: "SKU-PROD-004",
    name: "Aparador Vintage Provençal em Madeira Maciça (1,80x0,80m)",
    category: "Mobiliário & Cenografia",
    subcategory: "Aparadores",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 350.0,
    sellingPrice: 850.0,
    currentStock: 4,
    minStock: 1,
    maxStock: 10,
    supplierName: "Marcenaria Artesanal",
    location: "Depósito A1",
    mainPhoto: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&auto=format&fit=crop&q=80",
    description: "Aparador rústico trabalhado em madeira nobre estilo provençal com gavetas ornamentadas. Ideal para mesa de doces ou café festivo.",
  },
  {
    code: "PROD-005",
    sku: "SKU-PROD-005",
    name: "Arco de Balões Quadrado com Estrutura de Alumínio 3x3m",
    category: "Balões & Acessórios",
    subcategory: "Arcos Estruturados",
    brand: "Eliz Decora",
    unit: "UN",
    costPrice: 180.0,
    sellingPrice: 520.0,
    currentStock: 6,
    minStock: 2,
    maxStock: 15,
    supplierName: "Party Express",
    location: "Prateleira B2",
    mainPhoto: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=600&auto=format&fit=crop&q=80",
    description: "Estrutura desmontável de alumínio anodizado 3x3 metros para fixação rápida de arcos guirlanda de balões e tecidos em palcos.",
  },
  {
    code: "PROD-006",
    sku: "SKU-PROD-006",
    name: "Arco Desconstruído Orgânico de Balões 4 metros",
    category: "Balões & Acessórios",
    subcategory: "Arcos Orgânicos",
    brand: "Eliz Decora",
    unit: "UN",
    costPrice: 120.0,
    sellingPrice: 450.0,
    currentStock: 15,
    minStock: 3,
    maxStock: 30,
    supplierName: "Party Express",
    location: "Prateleira B1",
    mainPhoto: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&auto=format&fit=crop&q=80",
    description: "Arco orgânico com balões de látex premium em tamanhos variados (5 a 18 polegadas), acabamento brilhante e fixação de alta durabilidade.",
  },
  {
    code: "PROD-007",
    sku: "SKU-PROD-007",
    name: "Arco Romano em MDF para Painel Sublimado 2,10x1,00m",
    category: "Mobiliário & Cenografia",
    subcategory: "Painéis Romanos",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 220.0,
    sellingPrice: 680.0,
    currentStock: 8,
    minStock: 2,
    maxStock: 20,
    supplierName: "Painéis Brasil",
    location: "Depósito A2",
    mainPhoto: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&auto=format&fit=crop&q=80",
    description: "Estrutura curva formato arco romano em MDF reforçado com pé retrátil de sustentação. Suporta capas vestáveis sublimadas.",
  },
  {
    code: "PROD-008",
    sku: "SKU-PROD-008",
    name: "Argola para Guardanapo em Pérola e Metal Dourado (Jogo com 12 Unidades)",
    category: "Mesa Posta & Louçaria",
    subcategory: "Porta Guardanapos",
    brand: "Mesa Nobre",
    unit: "JG",
    costPrice: 35.0,
    sellingPrice: 110.0,
    currentStock: 20,
    minStock: 5,
    maxStock: 50,
    supplierName: "Louças & Cia",
    location: "Armário C1",
    mainPhoto: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&auto=format&fit=crop&q=80",
    description: "Anel prendedor de guardanapo banhado a ouro metálico ornamentado com pérolas sintéticas de alto brilho para jantares de luxo.",
  },
  {
    code: "PROD-009",
    sku: "SKU-PROD-009",
    name: "Arranjo Floral Comunitário para Mesa Principal 1,50m",
    category: "Flores, Folhagens & Vasos",
    subcategory: "Mesa Principal",
    brand: "Holambra",
    unit: "UN",
    costPrice: 90.0,
    sellingPrice: 320.0,
    currentStock: 10,
    minStock: 3,
    maxStock: 25,
    supplierName: "Holambra Flores",
    location: "Câmara Fria",
    mainPhoto: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=600&auto=format&fit=crop&q=80",
    description: "Composição floral rica com rosas importadas, hortênsias, lírios e folhagens nobres desidratadas para mesa de bolo ou convidados VIP.",
  },
  {
    code: "PROD-010",
    sku: "SKU-PROD-010",
    name: "Balão Bubble Transparentes 24 Polegadas (Pacote com 10 Unidades)",
    category: "Balões & Acessórios",
    subcategory: "Balões Especiais",
    brand: "Qualatex Pro",
    unit: "PK",
    costPrice: 60.0,
    sellingPrice: 180.0,
    currentStock: 25,
    minStock: 5,
    maxStock: 60,
    supplierName: "Party Express",
    location: "Prateleira B1",
    mainPhoto: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&auto=format&fit=crop&q=80",
    description: "Balões plásticos cristalinos ultra elásticos e resistentes. Aceita confetes, plumas ou LEDs internos para flutuação com gás hélio.",
  },
  {
    code: "PROD-011",
    sku: "SKU-PROD-011",
    name: "Balões Cromados e Metalizados Ouro Rosa 12' (Pacote com 50 Unidades)",
    category: "Balões & Acessórios",
    subcategory: "Balões Látex",
    brand: "Eliz Decora",
    unit: "PK",
    costPrice: 32.0,
    sellingPrice: 95.0,
    currentStock: 40,
    minStock: 10,
    maxStock: 100,
    supplierName: "Party Express",
    location: "Prateleira B1",
    mainPhoto: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=600&auto=format&fit=crop&q=80",
    description: "Balões de látex biodegradáveis de alta gramatura com acabamento espelhado tom ouro rosa (rose gold) metálico.",
  },
  {
    code: "PROD-012",
    sku: "SKU-PROD-012",
    name: "Biombo Vazado em MDF com Entalhe Mandalas (3 Folhas 1,80x1,50m)",
    category: "Mobiliário & Cenografia",
    subcategory: "Biombos & Painéis",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 260.0,
    sellingPrice: 650.0,
    currentStock: 3,
    minStock: 1,
    maxStock: 8,
    supplierName: "Marcenaria Artesanal",
    location: "Depósito A2",
    mainPhoto: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80",
    description: "Biombo dobrável em 3 painéis articulados de MDF 9mm cortado a laser com relevo de mandalas florais na cor branca ou amadeirada.",
  },
  {
    code: "PROD-013",
    sku: "SKU-PROD-013",
    name: "Boleira de Porcelana Branca com Borda Dourada 30cm",
    category: "Mesa Posta & Louçaria",
    subcategory: "Boleiras",
    brand: "Porcelanas Nobres",
    unit: "UN",
    costPrice: 65.0,
    sellingPrice: 180.0,
    currentStock: 12,
    minStock: 4,
    maxStock: 30,
    supplierName: "Louças & Cia",
    location: "Prateleira C1",
    mainPhoto: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80",
    description: "Boleira elevada em porcelana fina com acabamento nas bordas em filete dourado metálico. Diâmetro de 30cm para bolos de até 3 andares.",
  },
  {
    code: "PROD-014",
    sku: "SKU-PROD-014",
    name: "Bomba Elétrica Infladora para Balões de 2 Bicos 600W Bivolt",
    category: "Balões & Acessórios",
    subcategory: "Equipamentos",
    brand: "ProBalloons",
    unit: "UN",
    costPrice: 130.0,
    sellingPrice: 340.0,
    currentStock: 6,
    minStock: 2,
    maxStock: 12,
    supplierName: "Party Express",
    location: "Prateleira B3",
    mainPhoto: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&auto=format&fit=crop&q=80",
    description: "Compressor elétrico automático de alta pressão com acionamento por botão ou pressão nos bicos para agilizar montagem de arcos.",
  },
  {
    code: "PROD-015",
    sku: "SKU-PROD-015",
    name: "Box Truss Q25 Estrutura de Alumínio para Palco/Fundo 3x3m",
    category: "Mobiliário & Cenografia",
    subcategory: "Box Truss",
    brand: "Estruturas Pro",
    unit: "KT",
    costPrice: 550.0,
    sellingPrice: 1450.0,
    currentStock: 4,
    minStock: 1,
    maxStock: 8,
    supplierName: "Estruturas Brasil",
    location: "Depósito Externo",
    mainPhoto: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    description: "Grid quadrado em treliça pesada de alumínio Q25 com bases de apoio e parafusaria de engate rápido. Suporta iluminação e telas.",
  },
  {
    code: "PROD-016",
    sku: "SKU-PROD-016",
    name: "Cadeira Chiavari de Madeira Branca para Cerimonial",
    category: "Mobiliário & Cenografia",
    subcategory: "Cadeiras",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 95.0,
    sellingPrice: 280.0,
    currentStock: 80,
    minStock: 20,
    maxStock: 200,
    supplierName: "Móveis Festas",
    location: "Depósito C1",
    mainPhoto: "https://images.unsplash.com/photo-1503602642458-232111445657?w=600&auto=format&fit=crop&q=80",
    description: "Cadeira clássica italiana em madeira maciça laqueada em branco com assento almofadado em corino lavável.",
  },
  {
    code: "PROD-017",
    sku: "SKU-PROD-017",
    name: "Cadeira Infantil em Polipropileno Colorida (Kit com 4)",
    category: "Mobiliário & Cenografia",
    subcategory: "Cadeiras Infantis",
    brand: "Eliz Decora",
    unit: "JG",
    costPrice: 140.0,
    sellingPrice: 380.0,
    currentStock: 5,
    minStock: 2,
    maxStock: 15,
    supplierName: "Móveis Festas",
    location: "Depósito C2",
    mainPhoto: "https://images.unsplash.com/photo-1503602642458-232111445657?w=600&auto=format&fit=crop&q=80",
    description: "Conjunto de 4 cadeirinhas anatômicas resistentes para espaço kids e festas infantis. Suporta até 60kg por unidade.",
  },
  {
    code: "PROD-018",
    sku: "SKU-PROD-018",
    name: "Cadeira Louis Ghost Transparente em Policarbonato",
    category: "Mobiliário & Cenografia",
    subcategory: "Cadeiras",
    brand: "Design Lux",
    unit: "UN",
    costPrice: 120.0,
    sellingPrice: 320.0,
    currentStock: 40,
    minStock: 10,
    maxStock: 120,
    supplierName: "Móveis Festas",
    location: "Depósito C1",
    mainPhoto: "https://images.unsplash.com/photo-1503602642458-232111445657?w=600&auto=format&fit=crop&q=80",
    description: "Cadeira icônica transparente em policabonato injetado virgem de altíssima resistência e brilho cristalino.",
  },
  {
    code: "PROD-019",
    sku: "SKU-PROD-019",
    name: "Cadeira Tiffany de Madeira Dourada com Assento Estofado",
    category: "Mobiliário & Cenografia",
    subcategory: "Cadeiras",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 105.0,
    sellingPrice: 290.0,
    currentStock: 100,
    minStock: 30,
    maxStock: 250,
    supplierName: "Móveis Festas",
    location: "Depósito C1",
    mainPhoto: "https://images.unsplash.com/photo-1503602642458-232111445657?w=600&auto=format&fit=crop&q=80",
    description: "Cadeira tradicional Tiffany pintada na cor ouro imperial com almofada de assento removível e fixação por velcros.",
  },
  {
    code: "PROD-020",
    sku: "SKU-PROD-020",
    name: "Caixa Surpresa de Revelação para Balões 80x80cm",
    category: "Kits Temáticos & Sazonais",
    subcategory: "Chá Revelação",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 110.0,
    sellingPrice: 290.0,
    currentStock: 3,
    minStock: 1,
    maxStock: 8,
    supplierName: "Cenografia Criativa",
    location: "Depósito B1",
    mainPhoto: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600&auto=format&fit=crop&q=80",
    description: "Caixa cenográfica em MDF pintado com mecanismo de tampa de fácil abertura superior para liberação de balões com gás hélio.",
  },
  {
    code: "PROD-021",
    sku: "SKU-PROD-021",
    name: "Candelabro de Metal Dourado 5 Velas 75cm",
    category: "Iluminação & Efeitos",
    subcategory: "Velas & Castiçais",
    brand: "Lumière Lux",
    unit: "UN",
    costPrice: 160.0,
    sellingPrice: 420.0,
    currentStock: 8,
    minStock: 2,
    maxStock: 20,
    supplierName: "Illumina Festas",
    location: "Prateleira D1",
    mainPhoto: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600&auto=format&fit=crop&q=80",
    description: "Castiçal clássico imperial de 5 hastes em metal fundido dourado alto brilho. Excelente para jantares de casamento e festas de 15 anos.",
  },
  {
    code: "PROD-022",
    sku: "SKU-PROD-022",
    name: "Canhão de Papel Picado Chuva de Prata (Party Popper 60cm)",
    category: "Iluminação & Efeitos",
    subcategory: "Efeitos Especiais",
    brand: "Sparkler Festas",
    unit: "UN",
    costPrice: 18.0,
    sellingPrice: 55.0,
    currentStock: 50,
    minStock: 10,
    maxStock: 150,
    supplierName: "Party Express",
    location: "Armário F3",
    mainPhoto: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80",
    description: "Tubo de ar comprimido para acionamento manual que lança retalhos metalizados prateados e dourados a até 8 metros de altura.",
  },
  {
    code: "PROD-023",
    sku: "SKU-PROD-023",
    name: "Capim-dos-Pampas Seco Natural Selecionado (Haste 1,20m - Maço com 10)",
    category: "Flores, Folhagens & Vasos",
    subcategory: "Secos & Desidratados",
    brand: "Holambra",
    unit: "MC",
    costPrice: 45.0,
    sellingPrice: 135.0,
    currentStock: 18,
    minStock: 5,
    maxStock: 50,
    supplierName: "Holambra Flores",
    location: "Câmara Fria",
    mainPhoto: "https://images.unsplash.com/photo-1508615039623-a25605d2b022?w=600&auto=format&fit=crop&q=80",
    description: "Plumagens volumosas de capim-dos-pampas desidratado em tom bege natural para vasos de chão e arranjos suspensos boho chic.",
  },
  {
    code: "PROD-024",
    sku: "SKU-PROD-024",
    name: "Carrinho Bar Gourmet para Drinks, Pipoca e Brigadeiro",
    category: "Mobiliário & Cenografia",
    subcategory: "Carrinhos Gourmet",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 420.0,
    sellingPrice: 980.0,
    currentStock: 2,
    minStock: 1,
    maxStock: 5,
    supplierName: "Cenografia Criativa",
    location: "Depósito B2",
    mainPhoto: "https://images.unsplash.com/photo-1503602642458-232111445657?w=600&auto=format&fit=crop&q=80",
    description: "Carrinho cenográfico retrô em madeira pintada de branco com rodas decorativas e ombrelone listrado para balcão de guloseimas.",
  },
  {
    code: "PROD-025",
    sku: "SKU-PROD-025",
    name: "Castiçal de Vidro para Vela Rechaud (Jogo com 6 Unidades)",
    category: "Iluminação & Efeitos",
    subcategory: "Velas & Castiçais",
    brand: "Lumière Lux",
    unit: "JG",
    costPrice: 28.0,
    sellingPrice: 85.0,
    currentStock: 25,
    minStock: 5,
    maxStock: 60,
    supplierName: "Illumina Festas",
    location: "Armário C1",
    mainPhoto: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600&auto=format&fit=crop&q=80",
    description: "Copinhos de vidro lapidado transparência cristalina para velas réchaud, pontuando luz aconchegante nas mesas de convidados.",
  },
  {
    code: "PROD-026",
    sku: "SKU-PROD-026",
    name: "Cilindro MDF Revestido em Tecido Velvet (Jogo de 3 Peças)",
    category: "Mobiliário & Cenografia",
    subcategory: "Cilindros",
    brand: "Eliz Decora Pro",
    unit: "JG",
    costPrice: 280.0,
    sellingPrice: 750.0,
    currentStock: 7,
    minStock: 2,
    maxStock: 15,
    supplierName: "Marcenaria Artesanal",
    location: "Depósito A1",
    mainPhoto: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80",
    description: "Conjunto de 3 cilindros reforçados (tamanhos P, M e G) com capas aveludadas removíveis e laváveis.",
  },
  {
    code: "PROD-027",
    sku: "SKU-PROD-027",
    name: "Cilindro de Gás Hélio Descartável para 30 Balões",
    category: "Balões & Acessórios",
    subcategory: "Gás Hélio",
    brand: "Balloon Time",
    unit: "UN",
    costPrice: 190.0,
    sellingPrice: 420.0,
    currentStock: 10,
    minStock: 3,
    maxStock: 25,
    supplierName: "Party Express",
    location: "Depósito B3",
    mainPhoto: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&auto=format&fit=crop&q=80",
    description: "Botijão portátil e leve de gás hélio não inflamável pronto para uso com bico dosador para inflar balões de látex ou metalizados.",
  },
  {
    code: "PROD-028",
    sku: "SKU-PROD-028",
    name: "Coluna Romana Clássica em Resina Dourada 90cm",
    category: "Mobiliário & Cenografia",
    subcategory: "Colunas",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 140.0,
    sellingPrice: 380.0,
    currentStock: 6,
    minStock: 2,
    maxStock: 12,
    supplierName: "Cenografia Criativa",
    location: "Depósito A3",
    mainPhoto: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&auto=format&fit=crop&q=80",
    description: "Pedestal em resina acrílica lavável com acabamento em pátina dourada e ranhuras neoclássicas para sustentação de vasos e esculturas.",
  },
  {
    code: "PROD-029",
    sku: "SKU-PROD-029",
    name: "Conjunto de Sousplats de Rattan Natural Trançado (Jogo com 6 Unidades)",
    category: "Mesa Posta & Louçaria",
    subcategory: "Sousplats",
    brand: "Mesa Nobre",
    unit: "JG",
    costPrice: 85.0,
    sellingPrice: 240.0,
    currentStock: 15,
    minStock: 4,
    maxStock: 40,
    supplierName: "Louças & Cia",
    location: "Armário C2",
    mainPhoto: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&auto=format&fit=crop&q=80",
    description: "Pratos marcadores de mesa trançados artesanalmente em fibra de rattan natural. Ideal para eventos rústicos, praianos ou ao ar livre.",
  },
  {
    code: "PROD-030",
    sku: "SKU-PROD-030",
    name: "Cortina de Micro-Lâmpadas LED Warm White 3x3m",
    category: "Iluminação & Efeitos",
    subcategory: "Varais & Cortinas",
    brand: "Neon Flex",
    unit: "UN",
    costPrice: 85.0,
    sellingPrice: 240.0,
    currentStock: 14,
    minStock: 4,
    maxStock: 30,
    supplierName: "Illumina Festas",
    location: "Armário C3",
    mainPhoto: "https://images.unsplash.com/photo-1543589077-47d81606c1bf?w=600&auto=format&fit=crop&q=80",
    description: "Cortina luminosa com 300 micro LEDs branco quente fiação transparente 110/220V bivolt com 8 modos de pisca e luz fixa.",
  },
  {
    code: "PROD-031",
    sku: "SKU-PROD-031",
    name: "Descartáveis de Luxo: Pratos e Talheres Metalizados Dourados (Kit 50 Pessoas)",
    category: "Descartáveis de Luxo & Embalagens",
    subcategory: "Utensílios Descartáveis",
    brand: "Lux Party",
    unit: "KT",
    costPrice: 95.0,
    sellingPrice: 260.0,
    currentStock: 20,
    minStock: 5,
    maxStock: 50,
    supplierName: "Distribuidora Festas",
    location: "Armário D1",
    mainPhoto: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&auto=format&fit=crop&q=80",
    description: "Kit completo de refeição com pratos acrílicos reforçados e talheres com bordas banhadas em dourado rígido lavável.",
  },
  {
    code: "PROD-032",
    sku: "SKU-PROD-032",
    name: "Embalagens de Mimos: Saquinhos de Organza e Tubetes Cristal (Kit 100 Peças)",
    category: "Descartáveis de Luxo & Embalagens",
    subcategory: "Lembrancinhas",
    brand: "Lux Party",
    unit: "KT",
    costPrice: 40.0,
    sellingPrice: 120.0,
    currentStock: 30,
    minStock: 10,
    maxStock: 80,
    supplierName: "Distribuidora Festas",
    location: "Armário D2",
    mainPhoto: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80",
    description: "Conjunto para lembrancinhas contendo 50 saquinhos de organza com cordão de cetim e 50 tubetes acrílicos com tampa rosqueável.",
  },
  {
    code: "PROD-033",
    sku: "SKU-PROD-033",
    name: "Escada Decorativa de Madeira para Lembrancinhas 1,50m",
    category: "Mobiliário & Cenografia",
    subcategory: "Estantes",
    brand: "Eliz Decora",
    unit: "UN",
    costPrice: 130.0,
    sellingPrice: 340.0,
    currentStock: 6,
    minStock: 2,
    maxStock: 12,
    supplierName: "Marcenaria Artesanal",
    location: "Depósito B3",
    mainPhoto: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80",
    description: "Escada dobrável em madeira pinus lixada e envernizada com 4 prateleiras para exposição de mimos, suculentas e doces.",
  },
  {
    code: "PROD-034",
    sku: "SKU-PROD-034",
    name: "Espelho de Chão Barroco Dourado com Moldura Entalhada 1,80x0,80m",
    category: "Mobiliário & Cenografia",
    subcategory: "Instagramável",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 450.0,
    sellingPrice: 1200.0,
    currentStock: 2,
    minStock: 1,
    maxStock: 5,
    supplierName: "Vidraçaria Arte & Luxo",
    location: "Depósito A3",
    mainPhoto: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80",
    description: "Espelho bisotê de grande porte em moldura clássica barroca pintada em ouro envelhecido. Item instagramável para fotos de convidados.",
  },
  {
    code: "PROD-035",
    sku: "SKU-PROD-035",
    name: "Forminhas para Doces Finos em Tela Escócia (Caixa com 100 Unidades)",
    category: "Descartáveis de Luxo & Embalagens",
    subcategory: "Forminhas",
    brand: "Lux Party",
    unit: "CX",
    costPrice: 30.0,
    sellingPrice: 85.0,
    currentStock: 45,
    minStock: 10,
    maxStock: 100,
    supplierName: "Distribuidora Festas",
    location: "Armário D1",
    mainPhoto: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80",
    description: "Forminhas engomadas artesanais em tecido tela escócia formato flor de camélia para valorização de bombons e doces finos.",
  },
  {
    code: "PROD-036",
    sku: "SKU-PROD-036",
    name: "Globo Espelhado de Discoteca 40cm com Motor de Rotação 110/220V",
    category: "Iluminação & Efeitos",
    subcategory: "Efeitos Visuais",
    brand: "Disco Retro",
    unit: "UN",
    costPrice: 110.0,
    sellingPrice: 310.0,
    currentStock: 5,
    minStock: 2,
    maxStock: 10,
    supplierName: "Illumina Festas",
    location: "Armário C2",
    mainPhoto: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    description: "Globo de vidro espelhado de alta reflexão com motor elétrico síncrono silencioso e alça de suspensão reforçada para teto.",
  },
  {
    code: "PROD-037",
    sku: "SKU-PROD-037",
    name: "Guirlanda de Flores Secas e Capim dos Pampas 1,00m",
    category: "Flores, Folhagens & Vasos",
    subcategory: "Arranjos Suspensos",
    brand: "Holambra",
    unit: "UN",
    costPrice: 110.0,
    sellingPrice: 310.0,
    currentStock: 8,
    minStock: 2,
    maxStock: 20,
    supplierName: "Holambra Flores",
    location: "Câmara Fria",
    mainPhoto: "https://images.unsplash.com/photo-1508615039623-a25605d2b022?w=600&auto=format&fit=crop&q=80",
    description: "Guirlanda circular em aro de metal ornamentada com capim dos pampas, eucalipto preservado e flores secas boho chic.",
  },
  {
    code: "PROD-038",
    sku: "SKU-PROD-038",
    name: "Kit Banheiro de Emergência para Festas com Caixa Organizadora em MDF",
    category: "Pista de Dança & Animação",
    subcategory: "Kits Banheiro",
    brand: "Eliz Decora",
    unit: "KT",
    costPrice: 85.0,
    sellingPrice: 220.0,
    currentStock: 10,
    minStock: 3,
    maxStock: 20,
    supplierName: "Distribuidora Festas",
    location: "Armário F1",
    mainPhoto: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&auto=format&fit=crop&q=80",
    description: "Bandeja laqueada contendo itens de primeiros socorros e higiene (enxaguante, curativos, grampos, linha, agulha e analgésicos).",
  },
  {
    code: "PROD-039",
    sku: "SKU-PROD-039",
    name: "Kit Festa Junina Completo (Bandeirinhas, Toalha Xadrez e Chapéus de Palha)",
    category: "Kits Temáticos & Sazonais",
    subcategory: "Sazonalidade",
    brand: "Festas do Brasil",
    unit: "KT",
    costPrice: 90.0,
    sellingPrice: 280.0,
    currentStock: 8,
    minStock: 2,
    maxStock: 25,
    supplierName: "Distribuidora Festas",
    location: "Depósito Sazonal",
    mainPhoto: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&auto=format&fit=crop&q=80",
    description: "Kit temático com 100m de bandeirinhas coloridas de seda, toalha xadrez vermelha 3x2m e 10 chapéus de palha decorados.",
  },
  {
    code: "PROD-040",
    sku: "SKU-PROD-040",
    name: "Kit Pegue e Monte Temático Infantil (Painel, Cilindros e Toppers)",
    category: "Kits Temáticos & Sazonais",
    subcategory: "Festas Infantis",
    brand: "Eliz Decora",
    unit: "KT",
    costPrice: 180.0,
    sellingPrice: 520.0,
    currentStock: 12,
    minStock: 3,
    maxStock: 30,
    supplierName: "Cenografia Criativa",
    location: "Depósito B1",
    mainPhoto: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600&auto=format&fit=crop&q=80",
    description: "Kit completo portátil para festas em casa contendo painel circular sublimado, trio de capas de cilindros e displays de mesa.",
  },
  {
    code: "PROD-041",
    sku: "SKU-PROD-041",
    name: "Lanternas Marroquinas em Metal e Vidro (Trio P, M e G)",
    category: "Iluminação & Efeitos",
    subcategory: "Lanternas & Velas",
    brand: "Lumière Lux",
    unit: "JG",
    costPrice: 150.0,
    sellingPrice: 410.0,
    currentStock: 6,
    minStock: 2,
    maxStock: 15,
    supplierName: "Illumina Festas",
    location: "Armário C1",
    mainPhoto: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600&auto=format&fit=crop&q=80",
    description: "Conjunto de 3 lanternas rústicas vazadas em ferro envelhecido e vidros laterais para iluminação de chão ou passarela.",
  },
  {
    code: "PROD-042",
    sku: "SKU-PROD-042",
    name: "Letreiro Neon LED '15 Anos' Warm White Bivolt",
    category: "Iluminação & Efeitos",
    subcategory: "Neon LED",
    brand: "Neon Flex",
    unit: "UN",
    costPrice: 190.0,
    sellingPrice: 580.0,
    currentStock: 5,
    minStock: 2,
    maxStock: 10,
    supplierName: "Illumina Festas",
    location: "Armário C3",
    mainPhoto: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80",
    description: "Letreiro em acrílico cristal 6mm com fita neon flex branca quente 12V. Acompanha fonte bivolt e correntes de suspensão.",
  },
  {
    code: "PROD-043",
    sku: "SKU-PROD-043",
    name: "Letreiro Neon LED 'Let's Party' Rosa Magenta 80cm",
    category: "Iluminação & Efeitos",
    subcategory: "Neon LED",
    brand: "Neon Flex",
    unit: "UN",
    costPrice: 200.0,
    sellingPrice: 600.0,
    currentStock: 5,
    minStock: 2,
    maxStock: 15,
    supplierName: "Illumina Festas",
    location: "Armário C3",
    mainPhoto: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80",
    description: "Letreiro neon tubo de alta luminosidade na cor rosa magenta. Ideal para composição de fundo de mesa e arcos romanos.",
  },
  {
    code: "PROD-044",
    sku: "SKU-PROD-044",
    name: "Louça Suporte para Doces com 2 Andares em Vidro Lapidado",
    category: "Mesa Posta & Louçaria",
    subcategory: "Suportes de Doces",
    brand: "Porcelanas Nobres",
    unit: "UN",
    costPrice: 48.0,
    sellingPrice: 140.0,
    currentStock: 16,
    minStock: 5,
    maxStock: 40,
    supplierName: "Louças & Cia",
    location: "Prateleira C2",
    mainPhoto: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&auto=format&fit=crop&q=80",
    description: "Prato duplo para doces finos e macarons em vidro cristal trabalhado com haste central em metal rosé gold.",
  },
  {
    code: "PROD-045",
    sku: "SKU-PROD-045",
    name: "Máquina de Bolhas de Sabão Automática de Alta Vazão",
    category: "Iluminação & Efeitos",
    subcategory: "Efeitos Especiais",
    brand: "Sparkler Festas",
    unit: "UN",
    costPrice: 120.0,
    sellingPrice: 320.0,
    currentStock: 4,
    minStock: 1,
    maxStock: 10,
    supplierName: "Illumina Festas",
    location: "Armário C2",
    mainPhoto: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80",
    description: "Gerador elétrico de bolhas contínuas com motor giratório e reservatório de 1 litro para entrada de noivos e festas infantis.",
  },
  {
    code: "PROD-046",
    sku: "SKU-PROD-046",
    name: "Máquina de Fumaça DMX 1200W com Controle Sem Fio",
    category: "Iluminação & Efeitos",
    subcategory: "Efeitos Especiais",
    brand: "Sparkler Festas",
    unit: "UN",
    costPrice: 220.0,
    sellingPrice: 590.0,
    currentStock: 3,
    minStock: 1,
    maxStock: 8,
    supplierName: "Illumina Festas",
    location: "Armário C2",
    mainPhoto: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    description: "Equipamento para névoa cênica de alta densidade para pista de dança e valsa de 15 anos. Acompanha controle remoto rádio frequência.",
  },
  {
    code: "PROD-047",
    sku: "SKU-PROD-047",
    name: "Mesa Bistrô Alta Industrial com 2 Fezes de Ferro e Madeira",
    category: "Mobiliário & Cenografia",
    subcategory: "Mesas Bistrô",
    brand: "Eliz Decora Pro",
    unit: "JG",
    costPrice: 240.0,
    sellingPrice: 620.0,
    currentStock: 8,
    minStock: 2,
    maxStock: 20,
    supplierName: "Móveis Festas",
    location: "Depósito A1",
    mainPhoto: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&auto=format&fit=crop&q=80",
    description: "Mesa alta com estrutura em tubo de aço preto fosco e tampo redondo em peroba de demolição acompanhada de 2 banquetas.",
  },
  {
    code: "PROD-048",
    sku: "SKU-PROD-048",
    name: "Mesa Cavalete em Madeira Maciça Rústica 2,00x0,90m",
    category: "Mobiliário & Cenografia",
    subcategory: "Mesas Principais",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 320.0,
    sellingPrice: 790.0,
    currentStock: 4,
    minStock: 1,
    maxStock: 10,
    supplierName: "Marcenaria Artesanal",
    location: "Depósito A1",
    mainPhoto: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&auto=format&fit=crop&q=80",
    description: "Tampo em pranchão de peroba rosa com 2 cavaletes dobráveis. Estilo rústico chique de montagem rápida.",
  },
  {
    code: "PROD-049",
    sku: "SKU-PROD-049",
    name: "Mesa de Acrílico Cristal Transparente 1,50x0,80m",
    category: "Mobiliário & Cenografia",
    subcategory: "Mesas Principais",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 480.0,
    sellingPrice: 1100.0,
    currentStock: 3,
    minStock: 1,
    maxStock: 6,
    supplierName: "Acrílicos Design",
    location: "Depósito A2",
    mainPhoto: "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=600&auto=format&fit=crop&q=80",
    description: "Mesa moderna em acrílico virgem espessura 10mm, super límpida e resistente, perfeita para composições flutuantes.",
  },
  {
    code: "PROD-050",
    sku: "SKU-PROD-050",
    name: "Mesa com Pés Palito Estilo Retro Anos 60 (1,40x0,70m)",
    category: "Mobiliário & Cenografia",
    subcategory: "Mesas Principais",
    brand: "Eliz Decora",
    unit: "UN",
    costPrice: 210.0,
    sellingPrice: 560.0,
    currentStock: 4,
    minStock: 1,
    maxStock: 10,
    supplierName: "Marcenaria Artesanal",
    location: "Depósito A1",
    mainPhoto: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&auto=format&fit=crop&q=80",
    description: "Mesa de canto ovalizada com pés palito em madeira inclinados. Charmosa para pocket parties e festas de aniversário infantis.",
  },
  {
    code: "PROD-051",
    sku: "SKU-PROD-051",
    name: "Muro Inglês Artificial de Hera Premium (Módulo 2,00x1,00m)",
    category: "Mobiliário & Cenografia",
    subcategory: "Muro Inglês",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 160.0,
    sellingPrice: 420.0,
    currentStock: 8,
    minStock: 2,
    maxStock: 20,
    supplierName: "Painéis Brasil",
    location: "Depósito A2",
    mainPhoto: "https://images.unsplash.com/photo-1508615039623-a25605d2b022?w=600&auto=format&fit=crop&q=80",
    description: "Painel verde com folhagem densa de hera sintética anti-chamas. Proteção UV e encaixes modulares laterais.",
  },
  {
    code: "PROD-052",
    sku: "SKU-PROD-052",
    name: "Orquídeas Phalaenopsis Artificiais Toque Real em Vaso de Cerâmica",
    category: "Flores, Folhagens & Vasos",
    subcategory: "Flores Artificiais",
    brand: "Holambra",
    unit: "UN",
    costPrice: 75.0,
    sellingPrice: 210.0,
    currentStock: 12,
    minStock: 3,
    maxStock: 30,
    supplierName: "Holambra Flores",
    location: "Câmara Fria",
    mainPhoto: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=600&auto=format&fit=crop&q=80",
    description: "Hastes duplas de orquídeas brancas em silicone com textura idêntica à natural montadas em cachepot cerâmico espelhado.",
  },
  {
    code: "PROD-053",
    sku: "SKU-PROD-053",
    name: "Painel Circular em MDF Sublimado 2,00m (Tema Personalizável)",
    category: "Mobiliário & Cenografia",
    subcategory: "Painéis Circulares",
    brand: "Eliz Decora",
    unit: "UN",
    costPrice: 170.0,
    sellingPrice: 490.0,
    currentStock: 10,
    minStock: 3,
    maxStock: 25,
    supplierName: "Painéis Brasil",
    location: "Depósito A2",
    mainPhoto: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&auto=format&fit=crop&q=80",
    description: "Painel redondo dobrável com lona ou tecido vestácil sem vincos. Estrutura metálica de encaixe inclusa.",
  },
  {
    code: "PROD-054",
    sku: "SKU-PROD-054",
    name: "Painel Ripado de Freijó Natural 2,20x1,20m",
    category: "Mobiliário & Cenografia",
    subcategory: "Painéis Ripados",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 290.0,
    sellingPrice: 780.0,
    currentStock: 5,
    minStock: 2,
    maxStock: 12,
    supplierName: "Marcenaria Artesanal",
    location: "Depósito A1",
    mainPhoto: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80",
    description: "Módulo ripado elegante em madeira nobre tom freijó. Permite acoplar arranjos florais e letreiros neon.",
  },
  {
    code: "PROD-055",
    sku: "SKU-PROD-055",
    name: "Placas Divertidas para Fotos de Pista de Dança (Kit com 15 Frases)",
    category: "Pista de Dança & Animação",
    subcategory: "Placas de Fotos",
    brand: "Party Animações",
    unit: "KT",
    costPrice: 30.0,
    sellingPrice: 85.0,
    currentStock: 20,
    minStock: 5,
    maxStock: 50,
    supplierName: "Distribuidora Festas",
    location: "Armário F1",
    mainPhoto: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80",
    description: "Placas cartonadas rígidas com varetas plásticas contendo memes, frases de casamento, 15 anos e formaturas.",
  },
  {
    code: "PROD-056",
    sku: "SKU-PROD-056",
    name: "Poltrona Decorativa em Veludo Rosé para Lounge VIP",
    category: "Mobiliário & Cenografia",
    subcategory: "Poltronas & Sofás",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 280.0,
    sellingPrice: 720.0,
    currentStock: 4,
    minStock: 1,
    maxStock: 8,
    supplierName: "Móveis Festas",
    location: "Depósito A1",
    mainPhoto: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&auto=format&fit=crop&q=80",
    description: "Poltrona estofada estilo concha revestida em veludo macio toque suave na cor rosé com pés em tubo dourado.",
  },
  {
    code: "PROD-057",
    sku: "SKU-PROD-057",
    name: "Pratos de Servir e Travessas em Cerâmica Branca Bordada (Jogo 6 Peças)",
    category: "Mesa Posta & Louçaria",
    subcategory: "Travessas & Pratos",
    brand: "Porcelanas Nobres",
    unit: "JG",
    costPrice: 110.0,
    sellingPrice: 290.0,
    currentStock: 10,
    minStock: 3,
    maxStock: 25,
    supplierName: "Louças & Cia",
    location: "Prateleira C2",
    mainPhoto: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80",
    description: "Conjunto de travessas ovais e retangulares com relevo trabalhado nas bordas para composição de buffet e mesa comunitária.",
  },
  {
    code: "PROD-058",
    sku: "SKU-PROD-058",
    name: "Puff Capitonê Quadrado em Couro Sintético Branco",
    category: "Mobiliário & Cenografia",
    subcategory: "Puffs & Lounges",
    brand: "Eliz Decora",
    unit: "UN",
    costPrice: 70.0,
    sellingPrice: 190.0,
    currentStock: 16,
    minStock: 4,
    maxStock: 40,
    supplierName: "Móveis Festas",
    location: "Depósito C2",
    mainPhoto: "https://images.unsplash.com/photo-1503602642458-232111445657?w=600&auto=format&fit=crop&q=80",
    description: "Puff modular estofado 45x45cm com botões capitonê e revestimento impermeável de fácil higienização.",
  },
  {
    code: "PROD-059",
    sku: "SKU-PROD-059",
    name: "Refletor LED RGBW PAR 64 54x3W DMX Bivolt",
    category: "Iluminação & Efeitos",
    subcategory: "Refletores",
    brand: "Illumina Pro",
    unit: "UN",
    costPrice: 140.0,
    sellingPrice: 360.0,
    currentStock: 12,
    minStock: 4,
    maxStock: 30,
    supplierName: "Illumina Festas",
    location: "Armário C2",
    mainPhoto: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    description: "Canhão de luz LED RGBW de alta potência para iluminação cênica de paredes, painéis, árvores e fachadas.",
  },
  {
    code: "PROD-060",
    sku: "SKU-PROD-060",
    name: "Rosas de Toque Real e Peônias Artificiais Premium (Buquê com 12 Hastes)",
    category: "Flores, Folhagens & Vasos",
    subcategory: "Flores Artificiais",
    brand: "Holambra",
    unit: "BQ",
    costPrice: 55.0,
    sellingPrice: 160.0,
    currentStock: 20,
    minStock: 5,
    maxStock: 60,
    supplierName: "Holambra Flores",
    location: "Câmara Fria",
    mainPhoto: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=600&auto=format&fit=crop&q=80",
    description: "Hastadas de rosas aveludadas e peônias em seda toque real com tonalidades suaves e folhagem natural inclusa.",
  },
  {
    code: "PROD-061",
    sku: "SKU-PROD-061",
    name: "Sousplat de Vidro Espelhado com Borda Bisotada (Jogo com 6 Unidades)",
    category: "Mesa Posta & Louçaria",
    subcategory: "Sousplats",
    brand: "Mesa Nobre",
    unit: "JG",
    costPrice: 95.0,
    sellingPrice: 280.0,
    currentStock: 12,
    minStock: 3,
    maxStock: 30,
    supplierName: "Louças & Cia",
    location: "Armário C2",
    mainPhoto: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&auto=format&fit=crop&q=80",
    description: "Sousplats circulares de vidro espelhado 33cm com lapidação bisotê para mesa posta de alto luxo.",
  },
  {
    code: "PROD-062",
    sku: "SKU-PROD-062",
    name: "Taça Bico de Jaca Colorida para Água/Vinho 330ml (Jogo com 6 Unidades)",
    category: "Mesa Posta & Louçaria",
    subcategory: "Taças & Copos",
    brand: "Mesa Nobre",
    unit: "JG",
    costPrice: 70.0,
    sellingPrice: 190.0,
    currentStock: 18,
    minStock: 4,
    maxStock: 50,
    supplierName: "Louças & Cia",
    location: "Armário C3",
    mainPhoto: "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80",
    description: "Taças pesadas em vidro trabalhado em relevo bico de jaca nas cores Âmbar, Azul, Rosa ou Verde.",
  },
  {
    code: "PROD-063",
    sku: "SKU-PROD-063",
    name: "Tapete Sisal Trançado Natural para Passarela 10,00x1,20m",
    category: "Mobiliário & Cenografia",
    subcategory: "Passarelas & Tapetes",
    brand: "Eliz Decora",
    unit: "UN",
    costPrice: 210.0,
    sellingPrice: 590.0,
    currentStock: 4,
    minStock: 1,
    maxStock: 10,
    supplierName: "Tecidos & Taipas",
    location: "Depósito C1",
    mainPhoto: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=600&auto=format&fit=crop&q=80",
    description: "Passarela em fibra natural de sisal com debrum reforçado nas bordas. Indicada para casamentos no campo ou praia.",
  },
  {
    code: "PROD-064",
    sku: "SKU-PROD-064",
    name: "Toalha de Mesa em Jacquard Fendi com Maquinetado 3,00x3,00m",
    category: "Mesa Posta & Louçaria",
    subcategory: "Toalhas de Mesa",
    brand: "Mesa Nobre",
    unit: "UN",
    costPrice: 75.0,
    sellingPrice: 210.0,
    currentStock: 25,
    minStock: 8,
    maxStock: 60,
    supplierName: "Tecidos & Taipas",
    location: "Armário D2",
    mainPhoto: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&auto=format&fit=crop&q=80",
    description: "Toalha quadrada para mesa de convidados 10 lugares em tecido jacquard encorpado anti-manchas.",
  },
  {
    code: "PROD-065",
    sku: "SKU-PROD-065",
    name: "Topo de Bolo em Acrílico Espelhado Dourado Personalizado",
    category: "Papelaria & Topos de Bolo",
    subcategory: "Topos de Bolo",
    brand: "Papelaria Lux",
    unit: "UN",
    costPrice: 22.0,
    sellingPrice: 65.0,
    currentStock: 30,
    minStock: 5,
    maxStock: 100,
    supplierName: "Distribuidora Festas",
    location: "Armário E1",
    mainPhoto: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80",
    description: "Cake topper cortado a laser em acrílico 2mm com nomes dos noivos, idade de 15 anos ou frases de parabéns.",
  },
  {
    code: "PROD-066",
    sku: "SKU-PROD-066",
    name: "Torre de Doces de 3 Andares em Acrílico Cristal",
    category: "Mesa Posta & Louçaria",
    subcategory: "Suportes de Doces",
    brand: "Porcelanas Nobres",
    unit: "UN",
    costPrice: 50.0,
    sellingPrice: 150.0,
    currentStock: 10,
    minStock: 3,
    maxStock: 25,
    supplierName: "Louças & Cia",
    location: "Prateleira C2",
    mainPhoto: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&auto=format&fit=crop&q=80",
    description: "Torre piramidal de 3 pratos acrílicos transparentes para cupcakes, doces finos e salgados.",
  },
  {
    code: "PROD-067",
    sku: "SKU-PROD-067",
    name: "Trio de Cilindros Transparentes em Acrílico (P, M e G)",
    category: "Mobiliário & Cenografia",
    subcategory: "Cilindros",
    brand: "Eliz Decora Pro",
    unit: "JG",
    costPrice: 380.0,
    sellingPrice: 890.0,
    currentStock: 4,
    minStock: 1,
    maxStock: 10,
    supplierName: "Acrílicos Design",
    location: "Depósito A2",
    mainPhoto: "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=600&auto=format&fit=crop&q=80",
    description: "Conjunto de 3 cilindros ocos em acrílico virgem para preenchimento com balões, flores, luzes ou pelúcias.",
  },
  {
    code: "PROD-068",
    sku: "SKU-PROD-068",
    name: "Urso de Pelúcia Gigante Premium 1,50m para Decoração",
    category: "Kits Temáticos & Sazonais",
    subcategory: "Chá de Bebê",
    brand: "Eliz Decora",
    unit: "UN",
    costPrice: 190.0,
    sellingPrice: 480.0,
    currentStock: 3,
    minStock: 1,
    maxStock: 8,
    supplierName: "Pelúcias Magic",
    location: "Prateleira E1",
    mainPhoto: "https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=600&auto=format&fit=crop&q=80",
    description: "Urso gigante pelúcia antialérgica tom bege caramelo com laço de cetim. Destaque em chás de bebê e batizados.",
  },
  {
    code: "PROD-069",
    sku: "SKU-PROD-069",
    name: "Varal de Luzes Festim com Lâmpadas Filamento LED 20m",
    category: "Iluminação & Efeitos",
    subcategory: "Varais & Cortinas",
    brand: "Lumière Lux",
    unit: "UN",
    costPrice: 110.0,
    sellingPrice: 320.0,
    currentStock: 10,
    minStock: 3,
    maxStock: 25,
    supplierName: "Illumina Festas",
    location: "Armário C3",
    mainPhoto: "https://images.unsplash.com/photo-1543589077-47d81606c1bf?w=600&auto=format&fit=crop&q=80",
    description: "Cabo emborrachado preto com 20 soquetes E27 vedados contra chuva e lâmpadas vintage filamento LED âmbar.",
  },
  {
    code: "PROD-070",
    sku: "SKU-PROD-070",
    name: "Vaso Cachepot em Cerâmica Martelada Dourada 35cm",
    category: "Flores, Folhagens & Vasos",
    subcategory: "Vasos Decorativos",
    brand: "Porcelanas Nobres",
    unit: "UN",
    costPrice: 55.0,
    sellingPrice: 160.0,
    currentStock: 14,
    minStock: 4,
    maxStock: 35,
    supplierName: "Louças & Cia",
    location: "Prateleira C1",
    mainPhoto: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&auto=format&fit=crop&q=80",
    description: "Vaso bojudo em cerâmica esmaltada ouro metálico com superfície textura martelada para arranjos altos.",
  },
  {
    code: "PROD-071",
    sku: "SKU-PROD-071",
    name: "Vaso Solitário de Vidro Cristal para Mesa de Convidados 25cm",
    category: "Flores, Folhagens & Vasos",
    subcategory: "Vasos Decorativos",
    brand: "Porcelanas Nobres",
    unit: "UN",
    costPrice: 18.0,
    sellingPrice: 55.0,
    currentStock: 40,
    minStock: 10,
    maxStock: 100,
    supplierName: "Louças & Cia",
    location: "Prateleira C1",
    mainPhoto: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&auto=format&fit=crop&q=80",
    description: "Vaso fino e elegante de vidro soprado transparente para 1 a 3 hastes de rosas em mesas de convidados.",
  },
  {
    code: "PROD-072",
    sku: "SKU-PROD-072",
    name: "Vela de LED com Efeito Chama Viva Oscilante (Jogo com 6 Unidades)",
    category: "Iluminação & Efeitos",
    subcategory: "Lanternas & Velas",
    brand: "Lumière Lux",
    unit: "JG",
    costPrice: 35.0,
    sellingPrice: 105.0,
    currentStock: 20,
    minStock: 5,
    maxStock: 50,
    supplierName: "Illumina Festas",
    location: "Armário C1",
    mainPhoto: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600&auto=format&fit=crop&q=80",
    description: "Velas eletrônicas em cera sintética amarela com chama de LED balançante que simula a oscilação real do fogo.",
  },
  {
    code: "PROD-073",
    sku: "SKU-PROD-073",
    name: "Vela Faísca do Bolo Tipo Vulcão/Chuva de Prata (Pacote com 4 Unidades)",
    category: "Papelaria & Topos de Bolo",
    subcategory: "Velas de Aniversário",
    brand: "Sparkler Festas",
    unit: "PK",
    costPrice: 15.0,
    sellingPrice: 48.0,
    currentStock: 40,
    minStock: 10,
    maxStock: 120,
    supplierName: "Party Express",
    location: "Armário F3",
    mainPhoto: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80",
    description: "Velas pirotécnicas frias que produzem jorro de faíscas brilhantes de 30cm sem fumaça prejudicial para o parabéns.",
  }
]
