import { PrismaClient } from "@prisma/client"
import { PrismaLibSql } from "@prisma/adapter-libsql"

const adapter = new PrismaLibSql({ url: "file:dev.db" })
const prisma = new PrismaClient({ adapter })

export const partyProductsCatalog = [
  {
    code: "PROD-001",
    sku: "SKU-PROD-001",
    name: "Aparador Vintage Provençal em Madeira Maciça",
    category: "Mesas & Mobiliários",
    subcategory: "Aparadores",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 350.0,
    sellingPrice: 850.0,
    currentStock: 4,
    minStock: 1,
    maxStock: 10,
    supplierName: "Marcenaria Artesanal",
    location: "Depósito A1",
    mainPhoto: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&auto=format&fit=crop&q=80",
    description: "Aparador rústico trabalhado em madeira nobre estilo provençal (180x80cm). Ideal para mesa de doces, recepção ou café da manhã festivo.",
  },
  {
    code: "PROD-002",
    sku: "SKU-PROD-002",
    name: "Arco de Balões Quadrado com Estrutura de Alumínio 3x3m",
    category: "Balões & Arcos",
    subcategory: "Arcos Estruturados",
    brand: "Eliz Decora",
    unit: "UN",
    costPrice: 180.0,
    sellingPrice: 520.0,
    currentStock: 6,
    minStock: 2,
    maxStock: 15,
    supplierName: "Party Express",
    location: "Prateleira B2",
    mainPhoto: "https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=600&auto=format&fit=crop&q=80",
    description: "Estrutura desmontável de alumínio anodizado 3x3 metros para fixação rápida de arcos guirlanda de balões e tecidos.",
  },
  {
    code: "PROD-003",
    sku: "SKU-PROD-003",
    name: "Arco Desconstruído Orgânico de Balões 4 metros",
    category: "Balões & Arcos",
    subcategory: "Arcos Orgânicos",
    brand: "Eliz Decora",
    unit: "UN",
    costPrice: 120.0,
    sellingPrice: 450.0,
    currentStock: 15,
    minStock: 3,
    maxStock: 30,
    supplierName: "Party Express",
    location: "Prateleira B1",
    mainPhoto: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&auto=format&fit=crop&q=80",
    description: "Arco orgânico com balões de látex premium em tamanhos variados (5 a 18 polegadas), acabamento brilhante e fixação de alta durabilidade.",
  },
  {
    code: "PROD-004",
    sku: "SKU-PROD-004",
    name: "Arco Romano em MDF para Painel Sublimado 2,10x1,00m",
    category: "Painéis & Estruturas",
    subcategory: "Painéis Romanos",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 220.0,
    sellingPrice: 680.0,
    currentStock: 8,
    minStock: 2,
    maxStock: 20,
    supplierName: "Painéis Brasil",
    location: "Depósito A2",
    mainPhoto: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&auto=format&fit=crop&q=80",
    description: "Estrutura curva formato arco romano em MDF reforçado com pé retrátil de sustentação. Suporta capas vestáveis sublimadas.",
  },
  {
    code: "PROD-005",
    sku: "SKU-PROD-005",
    name: "Arranjo Floral Comunitário para Mesa Principal 1,50m",
    category: "Flores & Arranjos",
    subcategory: "Mesa Principal",
    brand: "Holambra",
    unit: "UN",
    costPrice: 90.0,
    sellingPrice: 320.0,
    currentStock: 10,
    minStock: 3,
    maxStock: 25,
    supplierName: "Holambra Flores",
    location: "Câmara Fria",
    mainPhoto: "https://images.unsplash.com/photo-1526047932273-341f2a7631f9?w=600&auto=format&fit=crop&q=80",
    description: "Composição floral rica com rosas importadas, hortênsias, lírios e folhagens nobres desidratadas para mesa de bolo ou convidados VIP.",
  },
  {
    code: "PROD-006",
    sku: "SKU-PROD-006",
    name: "Boleira de Porcelana Branca com Borda Dourada 30cm",
    category: "Louças & Boleiras",
    subcategory: "Boleiras",
    brand: "Porcelanas Nobres",
    unit: "UN",
    costPrice: 65.0,
    sellingPrice: 180.0,
    currentStock: 12,
    minStock: 4,
    maxStock: 30,
    supplierName: "Louças & Cia",
    location: "Prateleira C1",
    mainPhoto: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80",
    description: "Boleira elevada em porcelana fina com acabamento nas bordas em filete dourado metálico. Diâmetro de 30cm para bolos de até 3 andares.",
  },
  {
    code: "PROD-007",
    sku: "SKU-PROD-007",
    name: "Cadeira Infantil em Polipropileno Colorida (Kit com 4)",
    category: "Mesas & Mobiliários",
    subcategory: "Cadeiras",
    brand: "Eliz Decora",
    unit: "JG",
    costPrice: 140.0,
    sellingPrice: 380.0,
    currentStock: 5,
    minStock: 2,
    maxStock: 15,
    supplierName: "Móveis Festas",
    location: "Depósito C2",
    mainPhoto: "https://images.unsplash.com/photo-1503602642458-232111445657?w=600&auto=format&fit=crop&q=80",
    description: "Conjunto de 4 cadeirinhas anatômicas resistentes para espaço kids e festas infantis. Suporta até 60kg por unidade.",
  },
  {
    code: "PROD-008",
    sku: "SKU-PROD-008",
    name: "Caixa Surpresa de Revelação para Balões 80x80cm",
    category: "Cenários & Temas",
    subcategory: "Chá Revelação",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 110.0,
    sellingPrice: 290.0,
    currentStock: 3,
    minStock: 1,
    maxStock: 8,
    supplierName: "Cenografia Criativa",
    location: "Depósito B1",
    mainPhoto: "https://images.unsplash.com/photo-1513151233558-d860c5398176?w=600&auto=format&fit=crop&q=80",
    description: "Caixa cenográfica em MDF pintado com mecanismo de tampa de fácil abertura superior para liberação de balões com gás hélio.",
  },
  {
    code: "PROD-009",
    sku: "SKU-PROD-009",
    name: "Candelabro de Metal Dourado 5 Velas 75cm",
    category: "Iluminação & Neon",
    subcategory: "Velas & Castiçais",
    brand: "Lumière Lux",
    unit: "UN",
    costPrice: 160.0,
    sellingPrice: 420.0,
    currentStock: 8,
    minStock: 2,
    maxStock: 20,
    supplierName: "Illumina Festas",
    location: "Prateleira D1",
    mainPhoto: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?w=600&auto=format&fit=crop&q=80",
    description: "Castiçal clássico imperial de 5 hastes em metal fundido dourado alto brilho. Excelente para jantares de casamento e festas de 15 anos.",
  },
  {
    code: "PROD-010",
    sku: "SKU-PROD-010",
    name: "Cilindro MDF Revestido em Tecido Velvet (Jogo de 3 Peças)",
    category: "Mesas & Mobiliários",
    subcategory: "Cilindros",
    brand: "Eliz Decora Pro",
    unit: "JG",
    costPrice: 280.0,
    sellingPrice: 750.0,
    currentStock: 7,
    minStock: 2,
    maxStock: 15,
    supplierName: "Marcenaria Artesanal",
    location: "Depósito A1",
    mainPhoto: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80",
    description: "Conjunto de 3 cilindros reforçados (tamanhos P, M e G) com capas aveludadas removíveis e laváveis.",
  },
  {
    code: "PROD-011",
    sku: "SKU-PROD-011",
    name: "Cortina de Micro-Lâmpadas LED Warm White 3x3m",
    category: "Iluminação & Neon",
    subcategory: "Varais & Cortinas",
    brand: "Neon Flex",
    unit: "UN",
    costPrice: 85.0,
    sellingPrice: 240.0,
    currentStock: 14,
    minStock: 4,
    maxStock: 30,
    supplierName: "Illumina Festas",
    location: "Armário C3",
    mainPhoto: "https://images.unsplash.com/photo-1543589077-47d81606c1bf?w=600&auto=format&fit=crop&q=80",
    description: "Cortina luminosa com 300 micro LEDs branco quente fiação transparente 110/220V bivolt com 8 modos de pisca e luz fixa.",
  },
  {
    code: "PROD-012",
    sku: "SKU-PROD-012",
    name: "Escada Decorativa de Madeira para Lembrancinhas 1,50m",
    category: "Mesas & Mobiliários",
    subcategory: "Estantes",
    brand: "Eliz Decora",
    unit: "UN",
    costPrice: 130.0,
    sellingPrice: 340.0,
    currentStock: 6,
    minStock: 2,
    maxStock: 12,
    supplierName: "Marcenaria Artesanal",
    location: "Depósito B3",
    mainPhoto: "https://images.unsplash.com/photo-1513519245088-0e12902e5a38?w=600&auto=format&fit=crop&q=80",
    description: "Escada dobrável em madeira pinus lixada e envernizada com 4 prateleiras para exposição de mimos, suculentas e doces.",
  },
  {
    code: "PROD-013",
    sku: "SKU-PROD-013",
    name: "Espelho de Chão Barroco Dourado com Moldura Entalhada 1,80x0,80m",
    category: "Cenários & Temas",
    subcategory: "Instagramável",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 450.0,
    sellingPrice: 1200.0,
    currentStock: 2,
    minStock: 1,
    maxStock: 5,
    supplierName: "Vidraçaria Arte & Luxo",
    location: "Depósito A3",
    mainPhoto: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80",
    description: "Espelho bisotê de grande porte em moldura clássica barroca pintada em ouro envelhecido. Item instagramável para fotos de convidados.",
  },
  {
    code: "PROD-014",
    sku: "SKU-PROD-014",
    name: "Guirlanda de Flores Secas e Capim dos Pampas 1,00m",
    category: "Flores & Arranjos",
    subcategory: "Arranjos Suspensos",
    brand: "Holambra",
    unit: "UN",
    costPrice: 110.0,
    sellingPrice: 310.0,
    currentStock: 8,
    minStock: 2,
    maxStock: 20,
    supplierName: "Holambra Flores",
    location: "Câmara Fria",
    mainPhoto: "https://images.unsplash.com/photo-1508615039623-a25605d2b022?w=600&auto=format&fit=crop&q=80",
    description: "Guirlanda circular em aro de metal ornamentada com capim dos pampas, eucalipto preservado e flores secas boho chic.",
  },
  {
    code: "PROD-015",
    sku: "SKU-PROD-015",
    name: "Letreiro Neon LED '15 Anos' Warm White Bivolt",
    category: "Iluminação & Neon",
    subcategory: "Neon LED",
    brand: "Neon Flex",
    unit: "UN",
    costPrice: 190.0,
    sellingPrice: 580.0,
    currentStock: 5,
    minStock: 2,
    maxStock: 10,
    supplierName: "Illumina Festas",
    location: "Armário C3",
    mainPhoto: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80",
    description: "Letreiro em acrílico cristal 6mm com fita neon flex branca quente 12V. Acompanha fonte bivolt e correntes de suspensão.",
  },
  {
    code: "PROD-016",
    sku: "SKU-PROD-016",
    name: "Letreiro Neon LED 'Let's Party' Rosa Magenta 80cm",
    category: "Iluminação & Neon",
    subcategory: "Neon LED",
    brand: "Neon Flex",
    unit: "UN",
    costPrice: 200.0,
    sellingPrice: 600.0,
    currentStock: 5,
    minStock: 2,
    maxStock: 15,
    supplierName: "Illumina Festas",
    location: "Armário C3",
    mainPhoto: "https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80",
    description: "Letreiro neon tubo de alta luminosidade na cor rosa magenta. Ideal para composição de fundo de mesa e arcos romanos.",
  },
  {
    code: "PROD-017",
    sku: "SKU-PROD-017",
    name: "Louça Suporte para Doces com 2 Andares em Vidro Lapidado",
    category: "Louças & Boleiras",
    subcategory: "Suportes de Doces",
    brand: "Porcelanas Nobres",
    unit: "UN",
    costPrice: 48.0,
    sellingPrice: 140.0,
    currentStock: 16,
    minStock: 5,
    maxStock: 40,
    supplierName: "Louças & Cia",
    location: "Prateleira C2",
    mainPhoto: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?w=600&auto=format&fit=crop&q=80",
    description: "Prato duplo para doces finos e macarons em vidro cristal trabalhado com haste central em metal rosé gold.",
  },
  {
    code: "PROD-018",
    sku: "SKU-PROD-018",
    name: "Mesa Cavalete em Madeira Maciça Rústica 2,00x0,90m",
    category: "Mesas & Mobiliários",
    subcategory: "Mesas Principais",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 320.0,
    sellingPrice: 790.0,
    currentStock: 4,
    minStock: 1,
    maxStock: 10,
    supplierName: "Marcenaria Artesanal",
    location: "Depósito A1",
    mainPhoto: "https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&auto=format&fit=crop&q=80",
    description: "Tampo em pranchão de peroba rosa com 2 cavaletes dobráveis. Estilo rústico chique de montagem rápida.",
  },
  {
    code: "PROD-019",
    sku: "SKU-PROD-019",
    name: "Mesa de Acrílico Cristal Transparente 1,50x0,80m",
    category: "Mesas & Mobiliários",
    subcategory: "Mesas Principais",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 480.0,
    sellingPrice: 1100.0,
    currentStock: 3,
    minStock: 1,
    maxStock: 6,
    supplierName: "Acrílicos Design",
    location: "Depósito A2",
    mainPhoto: "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=600&auto=format&fit=crop&q=80",
    description: "Mesa moderna em acrílico virgem espessura 10mm, super límpida e resistente, perfeita para composições flutuantes.",
  },
  {
    code: "PROD-020",
    sku: "SKU-PROD-020",
    name: "Painel Circular em MDF Sublimado 2,00m (Tema Personalizável)",
    category: "Painéis & Estruturas",
    subcategory: "Painéis Circulares",
    brand: "Eliz Decora",
    unit: "UN",
    costPrice: 170.0,
    sellingPrice: 490.0,
    currentStock: 10,
    minStock: 3,
    maxStock: 25,
    supplierName: "Painéis Brasil",
    location: "Depósito A2",
    mainPhoto: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&auto=format&fit=crop&q=80",
    description: "Painel redondo dobrável com lona ou tecido vestácil sem vincos. Estrutura metálica de encaixe inclusa.",
  },
  {
    code: "PROD-021",
    sku: "SKU-PROD-021",
    name: "Painel Ripado de Freijó Natural 2,20x1,20m",
    category: "Painéis & Estruturas",
    subcategory: "Painéis Ripados",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 290.0,
    sellingPrice: 780.0,
    currentStock: 5,
    minStock: 2,
    maxStock: 12,
    supplierName: "Marcenaria Artesanal",
    location: "Depósito A1",
    mainPhoto: "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=600&auto=format&fit=crop&q=80",
    description: "Módulo ripado elegante em madeira nobre tom freijó. Permite acoplar arranjos florais e letreiros neon.",
  },
  {
    code: "PROD-022",
    sku: "SKU-PROD-022",
    name: "Pergolado em Madeira Nobre para Cerimonial 2,50x2,50m",
    category: "Cenários & Temas",
    subcategory: "Casamentos",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 650.0,
    sellingPrice: 1850.0,
    currentStock: 2,
    minStock: 1,
    maxStock: 4,
    supplierName: "Marcenaria Artesanal",
    location: "Depósito Externo",
    mainPhoto: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&auto=format&fit=crop&q=80",
    description: "Estrutura autoportante em vigas de maçaranduba tratada para alta estabilidade em eventos ao ar livre.",
  },
  {
    code: "PROD-023",
    sku: "SKU-PROD-023",
    name: "Refletor LED RGBW PAR 64 54x3W DMX Bivolt",
    category: "Iluminação & Neon",
    subcategory: "Refletores",
    brand: "Illumina Pro",
    unit: "UN",
    costPrice: 140.0,
    sellingPrice: 360.0,
    currentStock: 12,
    minStock: 4,
    maxStock: 30,
    supplierName: "Illumina Festas",
    location: "Armário C2",
    mainPhoto: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80",
    description: "Canhão de luz LED RGBW de alta potência para iluminação cênica de paredes, painéis, árvores e fachadas.",
  },
  {
    code: "PROD-024",
    sku: "SKU-PROD-024",
    name: "Tapete Sisal Trançado Natural para Passarela 10,00x1,20m",
    category: "Têxtil & Enxoval",
    subcategory: "Passarelas & Tapetes",
    brand: "Eliz Decora",
    unit: "UN",
    costPrice: 210.0,
    sellingPrice: 590.0,
    currentStock: 4,
    minStock: 1,
    maxStock: 10,
    supplierName: "Tecidos & Taipas",
    location: "Depósito C1",
    mainPhoto: "https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=600&auto=format&fit=crop&q=80",
    description: "Passarela em fibra natural de sisal com debrum reforçado nas bordas. Indicada para casamentos no campo ou praia.",
  },
  {
    code: "PROD-025",
    sku: "SKU-PROD-025",
    name: "Toalha de Mesa em Jacquard Fendi com Maquinetado 3,00x3,00m",
    category: "Têxtil & Enxoval",
    subcategory: "Toalhas de Mesa",
    brand: "Mesa Nobre",
    unit: "UN",
    costPrice: 75.0,
    sellingPrice: 210.0,
    currentStock: 25,
    minStock: 8,
    maxStock: 60,
    supplierName: "Tecidos & Taipas",
    location: "Armário D2",
    mainPhoto: "https://images.unsplash.com/photo-1519741497674-611481863552?w=600&auto=format&fit=crop&q=80",
    description: "Toalha quadrada para mesa de convidados 10 lugares em tecido jacquard encorpado anti-manchas.",
  },
  {
    code: "PROD-026",
    sku: "SKU-PROD-026",
    name: "Trio de Cilindros Transparentes em Acrílico (P, M e G)",
    category: "Mesas & Mobiliários",
    subcategory: "Cilindros",
    brand: "Eliz Decora Pro",
    unit: "JG",
    costPrice: 380.0,
    sellingPrice: 890.0,
    currentStock: 4,
    minStock: 1,
    maxStock: 10,
    supplierName: "Acrílicos Design",
    location: "Depósito A2",
    mainPhoto: "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?w=600&auto=format&fit=crop&q=80",
    description: "Conjunto de 3 cilindros ocos em acrílico virgem para preenchimento com balões, flores, luzes ou pelúcias.",
  },
  {
    code: "PROD-027",
    sku: "SKU-PROD-027",
    name: "Urso de Pelúcia Gigante Premium 1,50m para Decoração",
    category: "Cenários & Temas",
    subcategory: "Chá de Bebê",
    brand: "Eliz Decora",
    unit: "UN",
    costPrice: 190.0,
    sellingPrice: 480.0,
    currentStock: 3,
    minStock: 1,
    maxStock: 8,
    supplierName: "Pelúcias Magic",
    location: "Prateleira E1",
    mainPhoto: "https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=600&auto=format&fit=crop&q=80",
    description: "Urso gigante pelúcia antialérgica tom bege caramelo com laço de cetim. Destaque em chás de bebê e batizados.",
  },
  {
    code: "PROD-028",
    sku: "SKU-PROD-028",
    name: "Varal de Luzes Festim com Lâmpadas Filamento LED 20m",
    category: "Iluminação & Neon",
    subcategory: "Varais & Cortinas",
    brand: "Lumière Lux",
    unit: "UN",
    costPrice: 110.0,
    sellingPrice: 320.0,
    currentStock: 10,
    minStock: 3,
    maxStock: 25,
    supplierName: "Illumina Festas",
    location: "Armário C3",
    mainPhoto: "https://images.unsplash.com/photo-1543589077-47d81606c1bf?w=600&auto=format&fit=crop&q=80",
    description: "Cabo emborrachado preto com 20 soquetes E27 vedados contra chuva e lâmpadas vintage filamento LED âmbar.",
  },
  {
    code: "PROD-029",
    sku: "SKU-PROD-029",
    name: "Vaso Ornamental Cerâmica Dourada com Textura 45cm",
    category: "Louças & Boleiras",
    subcategory: "Vasos Decorativos",
    brand: "Porcelanas Nobres",
    unit: "UN",
    costPrice: 55.0,
    sellingPrice: 160.0,
    currentStock: 14,
    minStock: 4,
    maxStock: 35,
    supplierName: "Louças & Cia",
    location: "Prateleira C1",
    mainPhoto: "https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&auto=format&fit=crop&q=80",
    description: "Vaso bojudo em cerâmica esmaltada ouro metálico para arranjos altos de mesa principal.",
  },
  {
    code: "PROD-030",
    sku: "SKU-PROD-030",
    name: "Velotróis e Carrinho Gourmet para Pipoca e Brigadeiro",
    category: "Cenários & Temas",
    subcategory: "Carrinhos Gourmet",
    brand: "Eliz Decora Pro",
    unit: "UN",
    costPrice: 420.0,
    sellingPrice: 980.0,
    currentStock: 2,
    minStock: 1,
    maxStock: 5,
    supplierName: "Cenografia Criativa",
    location: "Depósito B2",
    mainPhoto: "https://images.unsplash.com/photo-1503602642458-232111445657?w=600&auto=format&fit=crop&q=80",
    description: "Carrinho cenográfico retrô em madeira pintada de branco com rodas decorativas e ombrelone listrado.",
  }
]

async function main() {
  console.log("Seeding Party Products Catalog in dev.db...")

  for (const item of partyProductsCatalog) {
    const category = await prisma.category.upsert({
      where: { name: item.category },
      update: {},
      create: {
        name: item.category,
        description: `Categoria profissional de ${item.category}`
      }
    })

    const supplier = await prisma.supplier.create({
      data: {
        companyName: item.supplierName,
        phone: "(11) 98888-0000"
      }
    }).catch(() => null)

    await prisma.product.upsert({
      where: { code: item.code },
      update: {
        sku: item.sku,
        name: item.name,
        subcategory: item.subcategory,
        brand: item.brand,
        unit: item.unit,
        costPrice: item.costPrice,
        sellingPrice: item.sellingPrice,
        currentStock: item.currentStock,
        minStock: item.minStock,
        maxStock: item.maxStock,
        location: item.location,
        mainPhoto: item.mainPhoto,
        description: item.description,
        categoryId: category.id,
        supplierId: supplier?.id || null,
      },
      create: {
        code: item.code,
        sku: item.sku,
        name: item.name,
        subcategory: item.subcategory,
        brand: item.brand,
        unit: item.unit,
        costPrice: item.costPrice,
        sellingPrice: item.sellingPrice,
        currentStock: item.currentStock,
        minStock: item.minStock,
        maxStock: item.maxStock,
        location: item.location,
        mainPhoto: item.mainPhoto,
        description: item.description,
        categoryId: category.id,
        supplierId: supplier?.id || null,
      }
    })
  }

  console.log("Party Products Catalog Seeded Successfully!")
}

if (require.main === module) {
  main()
    .catch((e) => {
      console.error(e)
      process.exit(1)
    })
    .finally(async () => {
      await prisma.$disconnect()
    })
}
